# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55de46b9ed1866f4098364e2e9443b4f4f78f96c6a3513f601ca8602c237c76b42d680fb9f5d605b0d674dabcde5786c03c6b853a066345c0ebd061fcce7f70e

test:
  secret_key_base: 84799a179effc041830979c78c2772df921399357bbe8037ec1287c900f94cd4fefef37409fa57d3f58683405aeede287300b456093f525b34479b903ac03698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
